### ISSUE TITLE
Future events in the past

### ISSUE THREAD

**Issue by RasmusWL** [datalogisk-fagraad/dikultur#24]
Currently there are events listed under `Future events` that happened in 2014 :(
http://dikultur.dk/events/

**Comment by valberg** [comment]
Hmm, yes - that is quite strange. As it should only show those where `start` > now. https://github.com/datalogisk-fagraad/dikultur/blob/master/apps/events/views.py#L15-L16

**Comment by valberg** [comment]
Ah! This is actually something that was fixed already, the code was just not in production because I've been waiting for @skjoenberg to pull his act together and finish that damn blog functionality.
Now everyone can see that he has not finished his work!
Mwhahaha!

**Comment by skjoenberg** [comment]
I'll finish it tomorrow, relax.

**Comment by RasmusWL** [comment]
This is still broken :(

**Comment by valberg** [comment]
Yeah I saw it as well - don't know why :S But it's fine now, don't know what happened.
